# Generated by Django 3.0.7 on 2021-05-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='date',
            new_name='created_on',
        ),
    ]
