# Generated by Django 3.0.7 on 2021-05-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_auto_20210504_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='is_featured',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
