# Generated by Django 3.0.7 on 2021-05-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_auto_20210504_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='is_featured',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
