# Generated by Django 3.0.7 on 2021-05-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_auto_20210504_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='is_featured',
            field=models.TextField(choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
