# Generated by Django 3.0.7 on 2021-05-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_auto_20210504_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='is_featured',
            field=models.CharField(choices=[('True', 'Yes'), ('False', 'No')], default='False', max_length=10, null=True),
        ),
    ]
