# Generated by Django 3.0.7 on 2021-05-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0014_events'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
