# Generated by Django 3.0.7 on 2021-05-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0015_auto_20210505_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
