# Generated by Django 3.0.7 on 2021-05-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0019_auto_20210505_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(upload_to=''),
        ),
    ]
