# Generated by Django 3.0.7 on 2021-05-05 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0020_auto_20210505_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='updated_at',
        ),
    ]
