# Generated by Django 3.0.7 on 2021-05-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0021_remove_events_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.ImageField(upload_to='users/%Y/%m/%d/'),
        ),
    ]
