# Generated by Django 3.0.7 on 2021-05-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0022_auto_20210505_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
