# Generated by Django 3.0.7 on 2021-05-05 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0023_auto_20210505_1813'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={},
        ),
        migrations.RenameField(
            model_name='events',
            old_name='image',
            new_name='featured_image',
        ),
        migrations.RemoveField(
            model_name='events',
            name='slug',
        ),
    ]
