# Generated by Django 3.0.7 on 2021-05-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0025_auto_20210505_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
