# Generated by Django 3.0.7 on 2021-05-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0027_auto_20210505_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='featured_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
