# Generated by Django 3.0.7 on 2021-05-05 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0028_auto_20210505_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='featured_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
