# Generated by Django 3.0.7 on 2021-05-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0029_auto_20210505_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='events/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.FileField(upload_to='profile/%Y/%m/%d'),
        ),
    ]
