# Generated by Django 3.0.7 on 2021-05-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0030_auto_20210505_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroCarousal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousal_image', models.ImageField(upload_to='carousal/')),
                ('url_link', models.URLField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
    ]
