# Generated by Django 3.0.7 on 2021-05-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0032_remove_herocarousal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocarousal',
            name='status',
            field=models.CharField(choices=[('Featured', 'Featured'), ('Not Featured', 'Not Featured')], default='Not Featured', max_length=15),
        ),
        migrations.AlterField(
            model_name='herocarousal',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='herocarousal',
            name='url_link',
            field=models.URLField(null=True),
        ),
    ]
