# Generated by Django 3.0.7 on 2021-05-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0033_auto_20210506_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herocarousal',
            old_name='title',
            new_name='alt_text',
        ),
        migrations.AddField(
            model_name='herocarousal',
            name='caption',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
