# Generated by Django 3.0.7 on 2021-05-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0034_auto_20210506_1846'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('department', models.CharField(blank=True, max_length=50)),
                ('designation', models.CharField(blank=True, max_length=50)),
                ('qualification', models.CharField(blank=True, max_length=150)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('awards', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='herocarousal',
            name='carousal_image',
            field=models.ImageField(null=True, upload_to='banner/'),
        ),
    ]
