# Generated by Django 3.0.7 on 2021-05-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0035_auto_20210507_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultymember',
            name='awards',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='experience',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='facultymember',
            name='qualification',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
